#ifndef SD_TRADING_VOLUME_BASELINE_H
#define SD_TRADING_VOLUME_BASELINE_H

#include <string>
#include <map>

namespace SDTrading {
namespace Utils {

/**
 * @class VolumeBaseline
 * @brief Manages time-of-day volume averages for normalization
 * 
 * Loads baseline from JSON file (generated by Python script).
 * Provides fast lookup for volume normalization during trading.
 */
class VolumeBaseline {
public:
    VolumeBaseline();
    ~VolumeBaseline() = default;
    
    /**
     * Load baseline from JSON file
     * @param filepath Path to volume_baseline.json
     * @return true if successful
     */
    bool load_from_file(const std::string& filepath);
    
    /**
     * Get normalized volume ratio
     * @param time_slot Time slot string (e.g., "09:15")
     * @param current_volume Current bar's volume
     * @return Ratio (current / baseline), or 1.0 if slot not found
     */
    double get_normalized_ratio(const std::string& time_slot, double current_volume) const;
    
    /**
     * Get baseline average for a time slot
     * @param time_slot Time slot string
     * @return Average volume, or 0 if not found
     */
    double get_baseline(const std::string& time_slot) const;
    
    /**
     * Check if baseline is loaded
     */
    bool is_loaded() const { return loaded_; }
    
    /**
     * Get number of time slots in baseline
     */
    size_t size() const { return baseline_map_.size(); }

    /**
     * Helper to extract time slot from datetime
     */
    std::string extract_time_slot(const std::string& datetime) const;

private:
    std::map<std::string, double> baseline_map_;  // time_slot -> avg_volume
    bool loaded_;
    
};

} // namespace Utils
} // namespace SDTrading

#endif // SD_TRADING_VOLUME_BASELINE_H
