// ============================================================
// LIVE DATA CSV READER FOR SD ENGINE V3.4
// Reads live_data.csv generated by Python bridge
// ============================================================

#ifndef LIVE_DATA_READER_H
#define LIVE_DATA_READER_H

#include "sd_engine_core.h"
#include <string>
#include <vector>
#include <fstream>
#include <sstream>
#include <chrono>
#include <thread>
#include <filesystem>
#include <iostream>
#include <ctime>

namespace fs = std::filesystem;

class LiveDataReader {
private:
    std::string csv_file_path_;
    std::time_t last_read_time_;
    std::vector<Bar> cached_bars_;
    int last_processed_index_;
    
    // Track file modification time
    std::filesystem::file_time_type last_file_time_;
    
public:
    LiveDataReader(const std::string& csv_path) 
        : csv_file_path_(csv_path)
        , last_read_time_(0)
        , last_processed_index_(0) {
        
        std::cout << "📂 LiveDataReader initialized" << std::endl;
        std::cout << "   CSV Path: " << csv_file_path_ << std::endl;
    }
    
    /**
     * Check if CSV file has been updated
     */
    bool has_new_data() {
        if (!fs::exists(csv_file_path_)) {
            return false;
        }
        
        auto current_time = fs::last_write_time(csv_file_path_);
        
        if (current_time != last_file_time_) {
            last_file_time_ = current_time;
            return true;
        }
        
        return false;
    }
    
    /**
     * Read all bars from CSV file
     * Returns only NEW bars since last read
     */
    std::vector<Bar> read_new_bars() {
        std::vector<Bar> all_bars = read_all_bars();
        
        if (all_bars.empty()) {
            return {};
        }
        
        // Return only bars we haven't processed yet
        if (last_processed_index_ >= (int)all_bars.size()) {
            return {}; // No new bars
        }
        
        std::vector<Bar> new_bars(
            all_bars.begin() + last_processed_index_,
            all_bars.end()
        );
        
        last_processed_index_ = (int)all_bars.size();
        
        if (!new_bars.empty()) {
            std::cout << "📊 Read " << new_bars.size() << " new bars from CSV" << std::endl;
        }
        
        return new_bars;
    }
    
    /**
     * Read all bars from CSV file
     */
    std::vector<Bar> read_all_bars() {
        std::vector<Bar> bars;
        
        std::ifstream file(csv_file_path_);
        if (!file.is_open()) {
            std::cerr << "❌ Cannot open CSV file: " << csv_file_path_ << std::endl;
            return bars;
        }
        
        std::string line;
        
        // Skip header
        if (!std::getline(file, line)) {
            return bars;
        }
        
        // Read data lines
        while (std::getline(file, line)) {
            if (line.empty()) continue;
            
            Bar bar = parse_csv_line(line);
            if (!bar.datetime.empty()) {
                bars.push_back(bar);
            }
        }
        
        file.close();
        return bars;
    }
    
    /**
     * Parse a CSV line into a Bar structure
     * Format: Timestamp,DateTime,Symbol,Open,High,Low,Close,Volume,OI
     */
    Bar parse_csv_line(const std::string& line) {
        Bar bar;
        
        std::stringstream ss(line);
        std::string field;
        int field_idx = 0;
        
        try {
            while (std::getline(ss, field, ',')) {
                switch (field_idx) {
                    case 0: // Timestamp (skip, we use datetime string)
                        break;
                    case 1: // DateTime
                        bar.datetime = field;
                        break;
                    case 2: // Symbol (skip)
                        break;
                    case 3: // Open
                        bar.open = std::stod(field);
                        break;
                    case 4: // High
                        bar.high = std::stod(field);
                        break;
                    case 5: // Low
                        bar.low = std::stod(field);
                        break;
                    case 6: // Close
                        bar.close = std::stod(field);
                        break;
                    case 7: // Volume
                        bar.volume = std::stod(field);
                        break;
                    case 8: // OI
                        bar.oi = std::stod(field);
                        break;
                }
                field_idx++;
            }
        } catch (const std::exception& e) {
            std::cerr << "⚠️ Parse error in line: " << line << std::endl;
            bar.datetime = ""; // Mark as invalid
        }
        
        return bar;
    }
    
    /**
     * Wait for new data with timeout
     * Returns true if new data arrived, false if timeout
     */
    bool wait_for_new_data(int timeout_seconds = 10) {
        auto start = std::chrono::steady_clock::now();
        
        while (true) {
            if (has_new_data()) {
                return true;
            }
            
            auto elapsed = std::chrono::duration_cast<std::chrono::seconds>(
                std::chrono::steady_clock::now() - start
            ).count();
            
            if (elapsed >= timeout_seconds) {
                return false;
            }
            
            std::this_thread::sleep_for(std::chrono::milliseconds(500));
        }
    }
    
    /**
     * Reset reader state (useful for replaying)
     */
    void reset() {
        last_processed_index_ = 0;
        last_read_time_ = 0;
        cached_bars_.clear();
        std::cout << "🔄 LiveDataReader reset" << std::endl;
    }
    
    /**
     * Get number of bars currently in CSV
     */
    int get_bar_count() {
        return (int)read_all_bars().size();
    }
};

#endif // LIVE_DATA_READER_H
